version: '2'
services:
  db:
    image: postgres:alpine
    volumes:
      - /var/run/postgresql:/var/run/postgresql:z
    ports:
      - 127.0.0.1:5435:5432/tcp
    cpu_shares: 256
    mem_limit: 1200000000
    environment:
      POSTGRES_PASSWORD: topsecret
      POSTGRES_DB: hotels
      POSTGRES_USER: backend

  web:
    image: api-hotels
    volumes:
      - .:/src:z
    command: bash -c "python manage.py runserver 0.0.0.0:8000"
    ports:
      - "80:8000"
